# Generated by Django 5.2.8 on 2025-11-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien'), ('administrateur', 'Administrateur')], default='client', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('statuts', models.CharField(choices=[('en attente', 'En attente'), ('en cours', 'En cours'), ('terminee', 'Terminée')], default='en attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaine_demandes', to='helpdeskapp.domaine')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_client', to='helpdeskapp.utilisateur')),
                ('technicien', models.ForeignKey(blank=True, limit_choices_to={'role': 'technicien'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicien_demandes', to='helpdeskapp.utilisateur')),
            ],
        ),
    ]
